openapi: 3.1.0
info:
  title: Transport Operator MaaS Provider API
  description: "<h2>Context</h2>
    <p>This API allows technical communication between Transport Operators (TO) and MaaS providers (MP, and other resellers), to fulfill a complete MaaS user journey<br>
    For more information: <a href='https://github.com/TOMP-WG/TOMP-API/wiki/OpenAPI-entry-page'>TOMP-API wiki</a>, and <a href='https://github.com/TOMP-WG/TOMP-API/wiki/OpenAPI-code-convention'>Coding conventions</a>"
  version: "2.0.0"
  contact:
    name: TOMP working group
    url: https://github.com/TOMP-WG/TOMP-API
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-modules:
    - customer management
    
tags:
  - name: customer management
    description: the <u>CUSTOMER MANAGEMENT MODULE</u> contains the functionality to explicitly manage the customer account on the TO side .

paths:
  /collections/customers/items:
    parameters:
      - $ref: "TOMP-API-1-CORE.yaml#/components/parameters/acceptLanguage"
    post:
      summary: "Create a TO CUSTOMER ACCOUNT for the customer"
      description: creates a CUSTOMER ACCOUNT that can be later used for purchase of a trip
      security:
        - BearerAuth: []
        - OAuth: []
        - OAuthPKI: []
      tags:
        - customer management
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/customer"
      responses:
        "201":
          $ref: "#/components/responses/customerResponse"
        default:
          $ref: "TOMP-API-1-CORE.yaml#/components/responses/errorResponse"
  
  /collections/customers/items/{customerId}:
    parameters:
      - name: customerId
        in: path
        required: true
        schema:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/customerReference"
    get:
      summary: "Get the customer account from the TO system"
      security:
        - BearerAuth: []
        - OAuth: []
        - OAuthPKI: []
      tags:
        - customer management
      responses:
        "200":
          $ref: "#/components/responses/customerResponse"
        default:
          $ref: "TOMP-API-1-CORE.yaml#/components/responses/errorResponse"
    patch:
      summary: "Update the CUSTOMER ACCOUNT on the TO system"
      description: updates the defined fields of the CUSTOMER ACCOUNT.<br>
      security:
        - BearerAuth: []
        - OAuth: []
        - OAuthPKI: []
      tags:
        - customer management
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              description: Patch object for Customer resource as defined by https://datatracker.ietf.org/doc/html/rfc7396
              $ref: "#/components/schemas/customer"
      responses:
        "200":
          $ref: "#/components/responses/customerResponse"
        default:
          $ref: "TOMP-API-1-CORE.yaml#/components/responses/errorResponse"
    delete:
      summary: "Delete the CUSTOMER ACCOUNT from the TO system."
      description: The timeline of deletion of the customer account depends on the TO processes, it could be instant, weeks or months.
      security:
        - BearerAuth: []
        - OAuth: []
        - OAuthPKI: []
      tags:
        - customer management
      responses:
        "200":
          description:  CUSTOMER ACCOUNT deleted successfully
        default:
          $ref: "TOMP-API-1-CORE.yaml#/components/responses/errorResponse"

components:
  responses:
    customerResponse:
      description: Customer Account
      x-semantics:
      - transmodel: none
      headers:
        Content-Language:
          $ref: "TOMP-API-1-CORE.yaml#/components/headers/contentLanguage"
        Version:
          $ref: "TOMP-API-1-CORE.yaml#/components/headers/version"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/customerAccount"

  schemas:
    customerAccount:
      x-semantics:
      - transmodel: CUSTOMER ACCOUNT
      description: A registration of the TRANSPORT CUSTOMER with an ACCOUNT PROVIDER to obtain travel services.
      type: object
      properties:
        id:
          $ref: "#/components/schemas/customer"
        creationDate:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/dateTime"
          description: The date in which the CUSTOMER ACCOUNT has been created
        modificationDate:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/dateTime"
          description: Last modification date of CUSTOMER ACCOUNT.
        status:
          $ref: "#/components/schemas/customerAccountStatus"
          description: The status of the CUSTOMER ACCOUNT

    customerAccountStatus:
      x-semantics:
      - transmodel: CUSTOMER ACCOUNT . status
      type: string
      description: status of a CUSTOMER ACCOUNT<br>
        _CREATED_ the customer account has been created but is not ready to create a purchase yet<br>
        _TO_PENDING_VALIDATION_ the customer account is pending a verification of identity and properties by the TO. No purchases can be made in this step<br>
        _OTP_REQUIRED_ the TO has sent an OTP to the customer's phone or email address and is expecting it to activate the account. No purchases can be made in this step<br>
        _ACTIVE_ the customer account is active and can continue to purchase offers<br>
        _BLOCKED_ the customer account has been blocked by the TO and can no longer use this TO<br>
      enum: [ CREATED, TO_PENDING_VALIDATION, ACTIVE, BLOCKED ]

    customer:
      x-semantics:
      - transmodel: TRANSPORT CUSTOMER
      description: A MaaS user that wishes to purchase a package, only use the fields required by purchase conditions
      type: object
      required:
        - id
      properties:
        id:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/customerReference"
          description: The identifier the MP uses to identify the customer. Could be an external referenced ID, like a ABT account number
        initials:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/tinyString"
          description: Initials of the customer
        firstName:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/shortString"
          description: First name of the customer
        lastName:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/shortString"
          description: Last name of the customer
        middleName:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/tinyString"
          description: Middle name of the customer
        prefix:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/tinyString"
          description: prefix of the customer, like titles
        postfix:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/tinyString"
          description: postfix of the customer, like titles
        phoneNumber:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/normalString"
        email:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/normalString"
          description: the email address of the customer
        dateOfBirth:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/date"
        placeOfBirth:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/shortString"
        countryOfBirth:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/shortString"
        address:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/place"
        photo:
          type: string
          maxLength: 10000
          description: base64 encoded
          x-format: byte-array
        extraInfo:
          $ref: "TOMP-API-1-CORE.yaml#/components/schemas/customProperties"