openapi: 3.0.0
info:
  title: Transport Operator MaaS Provider API - Technical extension
  description: This API extension allows to perform a health check    
  version: "1.0.0"
  contact:
    name: TOMP working group
    url: https://github.com/TOMP-WG/TOMP-API
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

tags:
  - name: tech
    description:
      technical support

paths:
  /health:
    get:
      operationId: ping
      tags:
        - tech
      summary: "is the API up and running?"
      description: "This is a healthcheck ENDPOINT"
      responses:
        "204":
          description: successful operation
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true

  /auth/token:
    post:
      operationId: get authentication token (JWT)
      tags:
        - tech
      description: "Request a JWT token"
      requestBody:
        content:
          application/json:
            schema:    
              type: object
              properties:
                user:
                  type: string
                password:
                  type: string
                certificate:
                  type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "404":
          $ref: "TOMP-API-CORE.yaml#/components/responses/errorResponse"
