@startuml Book-and-go
title Planning Scenario 'book-and-go' - V1.0.0
actor User
participant App

autoactivate on

note over User
I'm standing in front of asset x
and I want to travel now
end note
note over MP, TO
**ProcessIdentifiers**: ASSET_BASED, combined with
BLUETOOTH_SCAN, QR_SCAN, MANUAL_ENTRY,
NFC_SCAN or OTHER_ID.

In case you want to plan, book & open an asset
in one go, add ATOMIC_PLANNING_AND_BOOKING and 
(actually booking module) ATOMIC_BOOKING_UNLOCKING.
If you don't, the offers should be returned to the 
end user.
end note

User -> App: find out available asset
note over App
  first, find out the operators at the spot where
  the end user is.
  Do a bluetooth scan, scan a code, 
  enter a code on a bike, (RFID?), anything
  that uniquely identifies an asset, take into account
  the requirements of the TOs
end note

App -> MP : request planning options with this asset
note over MP
  It's time to contact the TOs with the found information 
  in the planning request.
end note

MP -> TO : prebook (booking-intent=true & asset info)\n/plannings/?booking-intent=true\n{... ,"useAssets": [ e.g. scanned QR code ] ...}
note over TO
  The TO should filter the results using the provided asset information 
  and also prebook the assets (no reservation yet!).
end note
return offer

== story continues in booking ==
@enduml
