@startuml book-from-map
title Planning Scenario 'book-from-map' - V1.0.0
actor User
participant App

autoactivate on

note over MP, TO
**ProcessIdentifiers**: ASSET_BASED and EXACT_ID

In case you want to plan, book & open an asset
in one go, add ATOMIC_PLANNING_AND_BOOKING and 
(actually booking module) ATOMIC_BOOKING_UNLOCKING.
If you don't, the offer should be returned to the 
end user.
end note

User -> App : show area map
App -> MP : show assets on map

MP -> TO : /operator/available-assets
return available assets
return available assets
return shows map

note over User
Looks at map, 
selects an asset 
end note

note over User, App
shows information about the asset 
(optionally request extra data using the /operator/information)
end note

User -> App : request booking of asset

App -> MP : request booking of this asset

MP -> TO : prebook (booking-intent=true & assetId in planningRequest) 
return single offer of the asset

== this story continues in booking ==
@enduml
