@startuml Planned trip
title Planning Scenario 'planned trip' - V1.0.0
actor User
participant App

autoactivate on

note over MP, TO
**ProcessIdentifiers** : PLANNING_BASED
The TO is allowed to return AssetTypes without real 
assets, only telling the number of available assets of
each type.
end note

User -> App : I want to travel from A to B\n leaving at C

App -> MP : I've got a user who wants\nto travel from A to B, leaving at C
note over MP
  the MP should doing some routing
  and find TOs in the area where the 
  planned trip will take place.
  Time to contact the selected TOs
end note

MP -> TO : look for planning options (optional)
note over TO
  planning options 
  without booking intent. The results don't have
  to be precise, but it must be likely that you can
  provide an asset for this trip.
end note
return likely legs

note over MP
  The MP gathers all results from the TOs. 
  Constructs the best trips - using the knowledge
  of how his end user likes to travel.
  Time to ask the TOs to 'prebook'
end note

MP -> TO : prebook (booking-intent=true)
note over TO
  the TO 'prebooks' the trips. It serves offers with a unique
  ID. This ID will remain the ID for the whole lifetime of 
  the trip.
  The result should contain real offers;
  there must be a high guarantee that the legs can be done
end note
return offers

note over MP
  The MP constructs the best suitable trips.
end note

return best trips

return best trips
@enduml
