@startuml Default operator information
title Planning Scenario 'default operator information' - V1.0.0
participant MP
participant Lookup
participant TO

autoactivate on

note over TO
**ProcessIdentifiers**: DEFAULT
end note

note over MP
Endpoints that could be used by the MP:
/operator/meta
/operator/available-assets
/operator/stations
/operator/regions
/operator/operating-calendar
/operator/operating-hours
/operator/pricing-plans
/operator/information
end note

MP -> TO : e.g. /operator/available-assets
return available assettypes (optionally containing assets)

note over Lookup
Endpoints that could be used by the MP:
/operator/meta
/operator/information
/operator/regions
end note

Lookup -> TO : e.g. /operator/meta
return precise description of the implementation of the API
@enduml
