@startuml Support
title Trip execution - changes - V1.0.0
participant MP
participant TO

autoactivate on

TO -> MP : PUT /legs/{id}
note over TO
The TO can make slight changes in the leg. 
The MP is allowed to reject the changes, but 
can accept them as long there are no financial
consequenses. In that case the current booking
should be cancelled and a new one should be 
added.
end note
return ok

@enduml
