@startuml finish-asset-by-TO
title Trip execution Scenario Part 'Close asset by TO' - V1.0.0

participant App
participant MP
participant TO
participant Asset

App -> MP : stop 
MP -> TO : /executions/{id}/events { "operation" : "FINISH" }
TO -> Asset: close
return ok
TO -> MP: ok

@enduml
