@startuml open-asset-by-app
title Trip execution Scenario Part 'Open asset by app' - V1.0.0

participant App
participant MP
participant TO
participant Asset

alt without processIdentifier 'ATOMIC_BOOKING_UNLOCKING'
  App -> MP : I want to start executing my booked leg
end

alt in case there is no asset assigned yet, but if it's needed
  MP -> TO : /executions/{id}/available-assets
  return available nearest assets
  MP -> App: show assets
  note right of App
  user must select one
  end note
  App -> MP : selected asset
  MP -> TO : /executions/{id}/events { "operation" : "ASSIGN_ASSET" }
  return ok
end

alt in case of 'ACCESS_CODE_IN_PREPARE_EVENT'
  MP -> TO : /executions/{id}/events { "operation" : "PREPARE" }
  return execution, in case of 'ACCESS_CODE_IN_PREPARE_EVENT'\nit must contain acces information
  MP -> App : open instructions
else in case the access instructions have already been provided
  note over MP
    The MP has received open instructions before (access code) in the
    result of the BOOKING or COMMIT event. This is dependent of the supplied
    processIdentifiers.
  end note
end

App -> Asset : open
note over App, MP
we are aware of the fact that this a very hard part to cover 
and the only generic solution that works is for now the deep link.
end note
return ok

App -> MP : bike opened
MP -> TO : /executions/{id}/events { "operation" : "SET_IN_USE" }
return ok

@enduml
