@startuml open-asset-by-TO
title Trip execution Scenario Part 'Open asset by TO' - V1.0.0

participant App
participant MP
participant TO
participant Asset

alt without processIdentifier 'ATOMIC_BOOKING_UNLOCKING'
  App -> MP : I want to start executing my booked leg
end

alt in case there is no asset assigned yet, but if it's needed
  MP -> TO : /executions/{id}/available-assets
  return available nearest assets
  MP -> App: show assets
  note right of App
  user must select one
  end note
  App -> MP : selected asset
  MP -> TO : /executions/{id}/events { "operation" : "ASSIGN_ASSET" }
  return ok
end

MP -> TO : /executions/{id}/events { "operation" : "SET_IN_USE" }
TO -> Asset: unlock
return ok
TO -> MP: ok

@enduml
