@startuml Trip execution - TO controlled
title Trip execution Scenario - to-controlled - V1.0.0
participant MP
participant TO

autoactivate on

alt USE_PREPARE_TO_INDICATE_START

note over MP
The taxi operator sends a PREPARE event 
whenever the taxi starts 
moving to the pickup point
end note

TO -> MP : /legs/{id}/events - PREPARE
return ok
end alt

alt ETA_NOTIFICATION
note over MP
The taxi operator sends notifications about
the ETA
end note

TO -> MP : /bookings/{id}/notifications - ETA - comment contains timestamp
return ok

TO -> MP : /bookings/{id}/notifications - ETA - comment="Arrived"
return ok
end alt

TO -> MP : /legs/{id}/events - SET_IN_USE
return ok

TO -> MP : /legs/{id}/events - FINISH
return ok

@enduml
