@startuml generated
class Asset {
 +String id
  Boolean isReserved
  String isReservedFrom
  String isReservedTo
  Boolean isDisabled
  String rentalUrl
  String rentalUrlAndroid
  String rentalUrlIOS
  Number mileage
  String licensePlate
}
Asset --  "1..1" AssetProperties : overriddenProperties >
class AssetProperties {
  String name
  Place location
  String fuel
  String energyLabel
  Number co2PerKm
  String brand
  String model
  Integer buildingYear
  Boolean travelAbroad
  Boolean airConditioning
  Boolean cabrio
  String colour
  String cargo
  String easyAccessibility
  Integer gears
  String gearbox
  String image
  Boolean infantSeat
  Integer persons
  Boolean pets
  String propulsion
  Boolean smoking
  Integer stateOfCharge
  Boolean towingHook
  Boolean undergroundParking
  Boolean winterTires
  Integer maxSpeed
  Boolean helmetRequired
  String other
  Integer nrOfDoors
  Object meta
  AssetAccessMethods[] accessMethods
}
note right of AssetProperties::fuel
NONE
GASOLINE
DIESEL
ELECTRIC
HYBRID_GASOLINE
HYBRID_DIESEL
HYBRID_GAS
HYDROGEN
GAS
BIO_MASS
KEROSINE
OTHER
end note
note right of AssetProperties::energyLabel
A B C D E
end note
note right of AssetProperties::easyAccessibility
LIFT
ESCALATOR
GROUND_LEVEL
SIGHTIMPAIRMENT
HEARINGIMPAIRMENT
WHEELCHAIR
end note
note right of AssetProperties::gearbox
MANUAL
AUTOMATIC
SEMIAUTOMATIC
end note
note right of AssetProperties::propulsion
MUSCLE
ELECTRIC
GASOLINE
DIESEL
HYBRID
LPG
HYDROGEN
end note
AssetProperties -left-{ Requirement : ancillaries >
class Requirement {
  String source
 +String category
 +String number
  String type
  String memo
  Integer variable-number
  String applicable-days
}
class AssetType {
 +String id
  String stationId
  Integer nrAvailable
  AssetClass assetClass
  String assetSubClass
  Condition[] conditions
  SystemPricingPlan[] applicablePricings
}
AssetType -{ Asset : assets >
AssetType --  "0..1" AssetProperties : sharedProperties >
@enduml
