@startuml generated
class Customer {
 +String id
  String travelerReference
  String initials
  String firstName
  String lastName
  String middleName
  String prefix
  String postfix
  Phone[] phones
  String email
  String birthDate
  Address address
  String photo
}
Customer -up-|> Traveler
Customer -{ Card : cards >
Customer -left-{ License : licenses >
class Traveler {
  Boolean isValidated
  Integer age
  String referenceNumber
  String knownIdentifier
  String knownIdentifierProvider
}
Traveler -{ CardType : cardTypes >
Traveler -left-{ LicenseType : licenseTypes >
Traveler -up-  "0..1" Requirements : requirements >
class CardType {
 +String type
  String subType
  AssetClass assetClass
  String acceptors
}
class LicenseType {
 +AssetClass assetClass
  Country issuingCountry
}
class Requirements {
}
Requirements -{ Requirement : abilities >
Requirements -{ Requirement : bringAlong >
class Requirement {
  String source
 +String category
 +String number
  String type
  String memo
  Integer variable-number
  String applicable-days
}
class Card {
  String cardDescription
 +String cardNumber
  String cardAdditionalNumber
 +String validUntil
  Country country
}
Card -up-|> CardType
class License {
  String number
  String licenseCode
  String validUntil
}
License -up-|> LicenseType
@enduml
