@startuml generated
class StationInformation {
 +String stationId
 +String name
 +Coordinates coordinates
  String crossStreet
  String regionId
  String rentalMethods
  String rentalUrl
  String rentalUrlAndroid
  String rentalUrlIOS
}
StationInformation --  "0..1" Address : physicalAddress >
class Address {
 +String streetAddress
  String street
  Integer houseNumber
  String houseNumberAddition
  String addressAdditionalInfo
 +String areaReference
  String city
  String province
  String state
  String postalCode
  Country country
}
class SystemAlert {
 +String alertId
 +String alertType
  String startAndEndTimes
  String stationIds
  String regionId
  String url
 +String summary
  String description
  String lastUpdated
}
class SystemCalendar {
  String stationId
  String regionId
 +Integer startMonth
 +Integer startDay
  Integer startYear
 +Integer endMonth
 +Integer endDay
  Integer endYear
}
class SystemHours {
  String userType
  String stationId
  String regionId
 +String startTime
 +String endTime
}
SystemHours -down-{ Day : days >
enum Day {
}
class SystemInformation {
 +String systemId
 +String language
 +String name
  String shortName
  String operator
  String url
  String purchaseUrl
  String discoveryUriAndroid
  String discoveryUriIOS
  String storeUriAndroid
  String storeUriIOS
  String startDate
  String phoneNumber
  String email
  String feedContactEmail
 +String timezone
  String licenseUrl
 +String typeOfSystem
  ChamberOfCommerceInfo chamberOfCommerceInfo
  String conditions
  String productType
  AssetClass[] assetClasses
}
class SystemPricingPlan {
 +String planId
  String url
 +String name
  String stationId
  String regionId
 +Fare fare
 +Boolean isTaxable
 +String description
}
class SystemRegion {
 +String regionId
 +String name
  String type
  String typeUnit
  Number typeValue
  String areaStartTime
  String areaEndTime
  GeojsonPolygon serviceArea
}
SystemInformation -down-{ SystemRegion
SystemInformation -down-{ StationInformation
SystemInformation -down-{ SystemPricingPlan
SystemInformation -down-{ SystemAlert
SystemInformation -down-{ SystemCalendar 
SystemInformation -down-{ SystemHours
@enduml
