@startuml 

package "Planning and booking" {
	[Traveler] -- [Travel right]
	[Travel right] -- [Asset]
}
package "Trip execution" {
	[Travel right] -right- [Operations]
}
package "Support" {
	[Travel right] -- [Support requests]
}
package "Payment" {
	[Travel right] -- [Journal entries]
}

@enduml