@startuml generated
class PlanningRequest {
  Integer radius
  Integer estimatedDistance
  String departureTime
  String arrivalTime
  Integer nrOfTravelers
  String useAssets
  String userGroups
  String useAssetTypes
}
PlanningRequest --  "1..1" Place : from >
PlanningRequest --  "0..1" Place : to >
PlanningRequest -{ Traveler : travelers >
class Place {
  String name
  StopReference[] stopReference
  String stationId
 +Coordinates coordinates
  Address physicalAddress
  Object extraInfo
}
class Traveler {
  Boolean isValidated
  Integer age
  String referenceNumber
  String knownIdentifier
  String knownIdentifierProvider
}
Traveler -up-{ CardType : cardTypes >
Traveler -{ LicenseType : licenseTypes >
Traveler --  "0..1" Requirements : requirements >
class CardType {
 +String type
  String subType
  AssetClass assetClass
  String acceptors
}
class LicenseType {
 +AssetClass assetClass
  Country issuingCountry
}
class Requirements {
}
Requirements -{ Requirement : abilities >
Requirements -{ Requirement : bringAlong >
class Requirement {
  String source
 +String category
 +String number
  String type
  String memo
  Integer variable-number
  String applicable-days
}
@enduml
