@startuml 

skinparam package {
	BorderStyle dotted
}

frame "Travel right"{
	Planning ..> BookingRequest
	Planning <.. PlanningRequest
	Booking <.. BookingRequest
	Booking =down={ Leg
	PlanningRequest -down-{ Place
	Leg --{ Condition
}

package "Asset" {
	Leg .right. AssetType
	Leg .right. Asset
	AssetType --{ Asset
}

@enduml