@startuml planning module

title Planning phase

set namespaceSeparator ::

request::planningRequest ..> result::planning : POST /plannings/
request::planningRequest -right-> request::place : from
request::planningRequest -right-> request::place : to
request::planningRequest -right-* request::traveler : travelers

request::planningRequest <|-- result::booking 
request::planningRequest <|-- result::leg

result::planning -left-* result::booking : options

result::booking -left-* result::leg : legs, normally 1
result::booking -down-> result::fare : pricing

result::leg -up-* result::condition
result::leg --> result::fare: pricing // empty, unless broker

class request::planningRequest {
    radius
    departureTime
    arrivalTime
    nrOfTravelers
    asset references
}
class result::planning {
    validuntil
}
class request::place {
    name
    coordinates
    <additional location references>
}
class request::traveler {
    age
    cardTypes eg payment, discount
    licenseTypes eg driver
    requirements eg disabilities
}
class result::booking {
    id : required when booking-intent=true
    customer // empty
    state = NEW
}
class result::leg {
    id // first leg in legs should have same id as booking
    state = NOT_STARTED
    assetType // optionally contains assets
    asset // empty, unless unique asset planned
    pricing // empty, unless broker
    suboperator // empty, unless broker
}
class result::condition {}
class result::fare {}


@enduml
