@startuml booking module

title booking: POST /bookings/

set namespaceSeparator ::

class request::bookingRequest extends planningRequest {
    id // booking-id from planning module
}

class request::customer extends traveler {
    id // maas-id
    name parts
    phones
    email
    birthdate
    address
    cards
    licenses
}

class result::booking extends request::bookingRequest {
    id 
    state = PENDING
}
class result::leg {
    id // first leg in legs should have same id as booking
    state = NOT_STARTED
    assetType // optionally contains assets
    asset // empty, unless unique asset booked
    pricing // empty, unless broker
    suboperator // empty, unless broker
}

class result::fare {}
class result::condition {}

request::bookingRequest -right-> request::customer
result::booking -left-* result::leg : legs, normally 1
result::booking -down-> result::fare : pricing

result::leg -up-* result::condition
result::leg --> result::fare: pricing // empty, unless broker

request::bookingRequest ..> result::booking : POST /bookings/

@enduml
