@startuml planned-trip

title TOMP API workflow - planned trip

start

floating note right: Green nodes are \nimplemented by TOMP API

partition "planning process" {
:Create routes;
#green:Search TOs for legs;
repeat
	if (offer required) then (yes)
		#green:Find out availability TOs;
		note right
		  /planning/inquiries
		end note
		#green:Prebook best routes;
		note right
		  /planning/offers
		end note
	else (no)
		:fetch external information\nfrom TO;
	endif 
repeat while(last TO?) is (no)
->:yes;
}

:Propose best trips to end user;

partition "booking process" {
repeat
	if (offer required) then (yes)
		#green:Book leg;
		note right
		  /bookings/
		end note
	else (no)
		#green:One stop booking leg;
		note right
		  /bookings/one-stop
		end note
	endif
repeat while(last TO?) is (no)
->:yes;
#green:Commit legs;
note right
  /bookings/{id}/events COMMIT
end note
}

partition "trip execution" {
repeat 
#green:Start leg;
note right
  /legs/{id}/events SET_IN_USE
end note
:Travel;
#green:Stop leg;
note right
  /legs/{id}/events FINISH
end note
repeat while (last leg?) is (no)
->:yes;
}

#green:Payment overview;
note right
  /payment/journal-entry
end note

stop

@enduml
