@startuml

title TOMP API workflow - postponed booking process

start

while (foreach leg)
  #green:Book leg per TO;
  if (booking ok?) then (yes)
  else (no)
    while (foreach booked leg)
      #green:Cancel leg;
    end while (ready)
    stop;
  endif
end while (ready)

while (foreach leg)
  #green:Commit leg;
  note right
    at least commit responds with a booking 
    in CONDITIONAL_CONFIRMED state
  end note
end while  (ready)

:wait for TO to respond;

if (TO responds) then (COMMIT)
else (DENY)
  :look for another solution, trip or TO;
endif

stop

@enduml