@startuml Support
title Support Scenario - V1.0.0
participant MP
participant TO

autoactivate on

note over MP
to facilitate reporting support issues, the
MP can call POST /support. To monitor the
progress the /support/{id}/status can be used
end note

MP -> TO : /support/
note over TO
The message should contain information about
the end user (=traveler) that is reporting the
issue for contact purposes (phone number),
the location and time and a priority.  
end note
return issue

note over MP
After creating an issue, the MP can monitor
the issue. The {id} is the id of the leg. 
end note

MP -> TO : /issue/{id}/status
return all statusses of the reported issue(s) on this leg

@enduml
