@startuml
class BookingRequest {
  String id
  String callbackUrl
}
BookingRequest --  "0..1" Place : from >
BookingRequest --  "0..1" Place : to >
BookingRequest --  "0..1" Customer : customer >
class Place {
  String name
  StopReference[] stopReference
  String stationId
 +Coordinates coordinates
  Address physicalAddress
  Object extraInfo
}
class Customer <<traveler>> {
 +String id
  String travelerReference
  String initials
  String firstName
  String lastName
  String middleName
  String prefix
  String postfix
  Phone[] phones
  String email
  String birthDate
  Address address
  String photo
  Card[] cards
  License[] licenses
}
@enduml
