@startuml 
class Booking <<bookingRequest>> {
  BookingState state
  Leg[] legs
  String departureTime
  String arrivalTime
  AssetType mainAssetType
  Object extraData
  Integer safeWaitTime
  Integer maxWaitTime
  Integer safeTravelTime
  Integer maxTravelTime
}
Booking --  "0..1" Fare : pricing >
class Fare {
 +Boolean estimated
  String description
  String class
}
Fare -{ FarePart : parts >
class FarePart {
  String type
  String kind
  String unitType
  Number units
  Number scaleFrom
  Number scaleTo
  String scaleType
  String name
  String class
  Number minimumAmount
  Number maximumAmount
  Object meta
}
FarePart -up-|> AmountOfMoney
class AmountOfMoney {
  Number amount
  Number amountExVat
  String currencyCode
  Number vatRate
  Country vatCountryCode
}
@enduml
