@startuml
class Place {
  String name
  String stationId
 +Coordinates coordinates
  Object extraInfo
}
Place -{ StopReference : stopReference >
Place --  "0..1" Address : physicalAddress >
class StopReference {
 +String type
 +String id
 +Country country
}
class Address {
 +String streetAddress
  String street
  Integer houseNumber
  String houseNumberAddition
  String addressAdditionalInfo
 +String areaReference
  String city
  String province
  String state
  String postalCode
  Country country
}
@enduml
