@startuml generated
class Planning {
 +String validUntil
}
Planning -{ Booking : options >
class Booking <<bookingRequest>> {
  BookingState state
  Leg[] legs
  Fare pricing
  String departureTime
  String arrivalTime
  AssetType mainAssetType
  Object extraData
  Integer safeWaitTime
  Integer maxWaitTime
  Integer safeTravelTime
  Integer maxTravelTime
}
@enduml
