@startuml generated
class Token {
 +String validFrom
 +String validUntil
 +String tokenType
}
Token --  "0..1" TokenData : tokenData >
class TokenQR {
 +String base64
  String version
}
TokenQR -up-|> TokenData
class TokenData {
 +String tokenType
}
class TokenArray {
}
class TokenDefault {
  String url
}
TokenDefault -up-|> TokenData
class TokenDeeplink {
  String url
  String knownParameters
}
TokenDeeplink -up-|> TokenData
class TokenEKey {
 +Object ekey
  String key
  Object passkey
  String bdAddress
  String deviceName
}
TokenEKey -up-|> TokenData

TokenArray -{ Token
@enduml
